#!/bin/bash

options=" lock\n logout\n  sleep\n  hibernate\n  reboot\n  shutdown"
selection=$(echo -e "${options}" | rofi -dmenu)

case "${selection}" in
    " lock")
        lock;;
    " logout")
        i3-msg exit;;
    "  sleep")
	systemctl suspend;;
    "  hibernate")
        systemctl hibernate;;
    "  reboot")
        systemctl reboot;;
    "  shutdown")
        systemctl poweroff -i;;
esac
